name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  repository:
    description: 'Who to greet'
    required: true
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repository }}